Repository lumicks/pylake, pull requests merged in 2021-11, with the labels that each got.

#187 Calibrate kymographs to base pairs
  changelog.md
  docs/tutorial/kymographs.rst
  lumicks/pylake/kymo.py
  lumicks/pylake/kymotracker/detail/calibrated_images.py
  lumicks/pylake/kymotracker/kymoline.py
  lumicks/pylake/kymotracker/tests/test_calibrated_images.py
  lumicks/pylake/kymotracker/tests/test_io.py
  lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
  lumicks/pylake/tests/test_kymo.py
Labels: enhancement, breaking change

#205 force_calibration: handle corner case fc < lbnd in analytic fit
  changelog.md
  lumicks/pylake/force_calibration/detail/power_models.py
  lumicks/pylake/force_calibration/tests/test_power_model.py
  lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Labels: bug

#217 kymotracker: allow changing slider ranges in the Kymotracker widget
  changelog.md
  docs/tutorial/kymotracking.rst
  lumicks/pylake/nb_widgets/kymotracker_widgets.py
  lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
Labels: enhancement
